version: "3.9"
services:
  bot:
    build:
      context: .
    restart: always
    env_file:
      - .env
    volumes:
      - ./bot-data:/app/bot-data
      - ./.config.json.tmp:/app/.config.json.tmp
      - type: bind
        source: ./config.json
        target: /app/config.json